#
# This file will be included by cmake/share/Files.cmake
#
# cmake/reflect/_Dependencies.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: DACD462C-D0AC-4D93-81A6-4E0972215046;MulleObjCOSFoundation;no-require,no-singlephase;
# Disable with : `mulle-sourcetree mark MulleObjCOSFoundation no-link`
# Disable for this platform: `mulle-sourcetree mark MulleObjCOSFoundation no-cmake-platform-darwin`
#
if( NOT MULLE_OBJC_OS_FOUNDATION_LIBRARY)
   find_library( MULLE_OBJC_OS_FOUNDATION_LIBRARY NAMES ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjCOSFoundation${CMAKE_STATIC_LIBRARY_SUFFIX} MulleObjCOSFoundation NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH)
   message( STATUS "MULLE_OBJC_OS_FOUNDATION_LIBRARY is ${MULLE_OBJC_OS_FOUNDATION_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE_OBJC_OS_FOUNDATION_LIBRARY)
      #
      # Add MULLE_OBJC_OS_FOUNDATION_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark MulleObjCOSFoundation no-cmake-add`
      #
      set( ALL_LOAD_DEPENDENCY_LIBRARIES
         ${ALL_LOAD_DEPENDENCY_LIBRARIES}
         ${MULLE_OBJC_OS_FOUNDATION_LIBRARY}
         CACHE INTERNAL "need to cache this"
      )
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark MulleObjCOSFoundation no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE_OBJC_OS_FOUNDATION_ROOT "${MULLE_OBJC_OS_FOUNDATION_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_OS_FOUNDATION_ROOT "${_TMP_MULLE_OBJC_OS_FOUNDATION_ROOT}" DIRECTORY)
      #
      #
      # Append header directory to user search path.
      # Disable with: `mulle-sourcetree mark MulleObjCOSFoundation no-cmake-searchpath`
      #
      foreach( _TMP_MULLE_OBJC_OS_FOUNDATION_NAME "MulleObjCOSFoundation")
         set( _TMP_MULLE_OBJC_OS_FOUNDATION_DIR "${_TMP_MULLE_OBJC_OS_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_OS_FOUNDATION_NAME}")
         if( IS_DIRECTORY "${_TMP_MULLE_OBJC_OS_FOUNDATION_DIR}")
            set( INHERITED_INCLUDE_DIRS
               ${INHERITED_INCLUDE_DIRS}
               "${_TMP_MULLE_OBJC_OS_FOUNDATION_DIR}"
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_OS_FOUNDATION_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark MulleObjCOSFoundation no-cmake-dependency`
      #
      foreach( _TMP_MULLE_OBJC_OS_FOUNDATION_NAME "MulleObjCOSFoundation")
         set( _TMP_MULLE_OBJC_OS_FOUNDATION_DIR "${_TMP_MULLE_OBJC_OS_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_OS_FOUNDATION_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( EXISTS "${_TMP_MULLE_OBJC_OS_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            unset( MULLE_OBJC_OS_FOUNDATION_DEFINITIONS)
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_OS_FOUNDATION_DIR}")
            #
            include( "${_TMP_MULLE_OBJC_OS_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            #
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_OS_FOUNDATION_DIR}")
            set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${MULLE_OBJC_OS_FOUNDATION_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_OS_FOUNDATION_DIR}/DependenciesAndLibraries.cmake not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCLoader+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark MulleObjCOSFoundation no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_MULLE_OBJC_OS_FOUNDATION_NAME "MulleObjCOSFoundation")
            set( _TMP_MULLE_OBJC_OS_FOUNDATION_FILE "${_TMP_MULLE_OBJC_OS_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_OS_FOUNDATION_NAME}/MulleObjCLoader+${_TMP_MULLE_OBJC_OS_FOUNDATION_NAME}.h")
            if( EXISTS "${_TMP_MULLE_OBJC_OS_FOUNDATION_FILE}")
               set( INHERITED_OBJC_LOADERS
                  ${INHERITED_OBJC_LOADERS}
                  ${_TMP_MULLE_OBJC_OS_FOUNDATION_FILE}
                  CACHE INTERNAL "need to cache this"
               )
               break()
            endif()
         endforeach()
      endif()
   else()
      # Enable with: `mulle-sourcetree mark MulleObjCOSFoundation require`
      message( STATUS "MULLE_OBJC_OS_FOUNDATION_LIBRARY is missing but it is marked as \"no-require\"")
   endif()
endif()


#
# Generated from sourcetree: 3C6EAD75-99C0-482F-AAA7-CFB194733AEC;MulleObjCKVCFoundation;no-require,no-singlephase;
# Disable with : `mulle-sourcetree mark MulleObjCKVCFoundation no-link`
# Disable for this platform: `mulle-sourcetree mark MulleObjCKVCFoundation no-cmake-platform-darwin`
#
if( NOT MULLE_OBJC_KVC_FOUNDATION_LIBRARY)
   find_library( MULLE_OBJC_KVC_FOUNDATION_LIBRARY NAMES ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjCKVCFoundation${CMAKE_STATIC_LIBRARY_SUFFIX} MulleObjCKVCFoundation NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH)
   message( STATUS "MULLE_OBJC_KVC_FOUNDATION_LIBRARY is ${MULLE_OBJC_KVC_FOUNDATION_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE_OBJC_KVC_FOUNDATION_LIBRARY)
      #
      # Add MULLE_OBJC_KVC_FOUNDATION_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark MulleObjCKVCFoundation no-cmake-add`
      #
      set( ALL_LOAD_DEPENDENCY_LIBRARIES
         ${ALL_LOAD_DEPENDENCY_LIBRARIES}
         ${MULLE_OBJC_KVC_FOUNDATION_LIBRARY}
         CACHE INTERNAL "need to cache this"
      )
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark MulleObjCKVCFoundation no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE_OBJC_KVC_FOUNDATION_ROOT "${MULLE_OBJC_KVC_FOUNDATION_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_KVC_FOUNDATION_ROOT "${_TMP_MULLE_OBJC_KVC_FOUNDATION_ROOT}" DIRECTORY)
      #
      #
      # Append header directory to user search path.
      # Disable with: `mulle-sourcetree mark MulleObjCKVCFoundation no-cmake-searchpath`
      #
      foreach( _TMP_MULLE_OBJC_KVC_FOUNDATION_NAME "MulleObjCKVCFoundation")
         set( _TMP_MULLE_OBJC_KVC_FOUNDATION_DIR "${_TMP_MULLE_OBJC_KVC_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_KVC_FOUNDATION_NAME}")
         if( IS_DIRECTORY "${_TMP_MULLE_OBJC_KVC_FOUNDATION_DIR}")
            set( INHERITED_INCLUDE_DIRS
               ${INHERITED_INCLUDE_DIRS}
               "${_TMP_MULLE_OBJC_KVC_FOUNDATION_DIR}"
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_KVC_FOUNDATION_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark MulleObjCKVCFoundation no-cmake-dependency`
      #
      foreach( _TMP_MULLE_OBJC_KVC_FOUNDATION_NAME "MulleObjCKVCFoundation")
         set( _TMP_MULLE_OBJC_KVC_FOUNDATION_DIR "${_TMP_MULLE_OBJC_KVC_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_KVC_FOUNDATION_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( EXISTS "${_TMP_MULLE_OBJC_KVC_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            unset( MULLE_OBJC_KVC_FOUNDATION_DEFINITIONS)
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_KVC_FOUNDATION_DIR}")
            #
            include( "${_TMP_MULLE_OBJC_KVC_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            #
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_KVC_FOUNDATION_DIR}")
            set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${MULLE_OBJC_KVC_FOUNDATION_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_KVC_FOUNDATION_DIR}/DependenciesAndLibraries.cmake not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCLoader+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark MulleObjCKVCFoundation no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_MULLE_OBJC_KVC_FOUNDATION_NAME "MulleObjCKVCFoundation")
            set( _TMP_MULLE_OBJC_KVC_FOUNDATION_FILE "${_TMP_MULLE_OBJC_KVC_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_KVC_FOUNDATION_NAME}/MulleObjCLoader+${_TMP_MULLE_OBJC_KVC_FOUNDATION_NAME}.h")
            if( EXISTS "${_TMP_MULLE_OBJC_KVC_FOUNDATION_FILE}")
               set( INHERITED_OBJC_LOADERS
                  ${INHERITED_OBJC_LOADERS}
                  ${_TMP_MULLE_OBJC_KVC_FOUNDATION_FILE}
                  CACHE INTERNAL "need to cache this"
               )
               break()
            endif()
         endforeach()
      endif()
   else()
      # Enable with: `mulle-sourcetree mark MulleObjCKVCFoundation require`
      message( STATUS "MULLE_OBJC_KVC_FOUNDATION_LIBRARY is missing but it is marked as \"no-require\"")
   endif()
endif()


#
# Generated from sourcetree: 41549518-5DAC-4A6A-82A9-E2CAABE3828F;MulleObjCDecimalFoundation;no-require,no-singlephase;
# Disable with : `mulle-sourcetree mark MulleObjCDecimalFoundation no-link`
# Disable for this platform: `mulle-sourcetree mark MulleObjCDecimalFoundation no-cmake-platform-darwin`
#
if( NOT MULLE_OBJC_DECIMAL_FOUNDATION_LIBRARY)
   find_library( MULLE_OBJC_DECIMAL_FOUNDATION_LIBRARY NAMES ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjCDecimalFoundation${CMAKE_STATIC_LIBRARY_SUFFIX} MulleObjCDecimalFoundation NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH)
   message( STATUS "MULLE_OBJC_DECIMAL_FOUNDATION_LIBRARY is ${MULLE_OBJC_DECIMAL_FOUNDATION_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE_OBJC_DECIMAL_FOUNDATION_LIBRARY)
      #
      # Add MULLE_OBJC_DECIMAL_FOUNDATION_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark MulleObjCDecimalFoundation no-cmake-add`
      #
      set( ALL_LOAD_DEPENDENCY_LIBRARIES
         ${ALL_LOAD_DEPENDENCY_LIBRARIES}
         ${MULLE_OBJC_DECIMAL_FOUNDATION_LIBRARY}
         CACHE INTERNAL "need to cache this"
      )
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark MulleObjCDecimalFoundation no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE_OBJC_DECIMAL_FOUNDATION_ROOT "${MULLE_OBJC_DECIMAL_FOUNDATION_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_DECIMAL_FOUNDATION_ROOT "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_ROOT}" DIRECTORY)
      #
      #
      # Append header directory to user search path.
      # Disable with: `mulle-sourcetree mark MulleObjCDecimalFoundation no-cmake-searchpath`
      #
      foreach( _TMP_MULLE_OBJC_DECIMAL_FOUNDATION_NAME "MulleObjCDecimalFoundation")
         set( _TMP_MULLE_OBJC_DECIMAL_FOUNDATION_DIR "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_NAME}")
         if( IS_DIRECTORY "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_DIR}")
            set( INHERITED_INCLUDE_DIRS
               ${INHERITED_INCLUDE_DIRS}
               "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_DIR}"
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark MulleObjCDecimalFoundation no-cmake-dependency`
      #
      foreach( _TMP_MULLE_OBJC_DECIMAL_FOUNDATION_NAME "MulleObjCDecimalFoundation")
         set( _TMP_MULLE_OBJC_DECIMAL_FOUNDATION_DIR "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( EXISTS "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            unset( MULLE_OBJC_DECIMAL_FOUNDATION_DEFINITIONS)
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_DIR}")
            #
            include( "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            #
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_DIR}")
            set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${MULLE_OBJC_DECIMAL_FOUNDATION_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_DIR}/DependenciesAndLibraries.cmake not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCLoader+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark MulleObjCDecimalFoundation no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_MULLE_OBJC_DECIMAL_FOUNDATION_NAME "MulleObjCDecimalFoundation")
            set( _TMP_MULLE_OBJC_DECIMAL_FOUNDATION_FILE "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_NAME}/MulleObjCLoader+${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_NAME}.h")
            if( EXISTS "${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_FILE}")
               set( INHERITED_OBJC_LOADERS
                  ${INHERITED_OBJC_LOADERS}
                  ${_TMP_MULLE_OBJC_DECIMAL_FOUNDATION_FILE}
                  CACHE INTERNAL "need to cache this"
               )
               break()
            endif()
         endforeach()
      endif()
   else()
      # Enable with: `mulle-sourcetree mark MulleObjCDecimalFoundation require`
      message( STATUS "MULLE_OBJC_DECIMAL_FOUNDATION_LIBRARY is missing but it is marked as \"no-require\"")
   endif()
endif()


#
# Generated from sourcetree: 1D103583-A637-4819-9255-3A265C80E49A;MulleObjCCalendarFoundation;no-require,no-singlephase;
# Disable with : `mulle-sourcetree mark MulleObjCCalendarFoundation no-link`
# Disable for this platform: `mulle-sourcetree mark MulleObjCCalendarFoundation no-cmake-platform-darwin`
#
if( NOT MULLE_OBJC_CALENDAR_FOUNDATION_LIBRARY)
   find_library( MULLE_OBJC_CALENDAR_FOUNDATION_LIBRARY NAMES ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjCCalendarFoundation${CMAKE_STATIC_LIBRARY_SUFFIX} MulleObjCCalendarFoundation NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH)
   message( STATUS "MULLE_OBJC_CALENDAR_FOUNDATION_LIBRARY is ${MULLE_OBJC_CALENDAR_FOUNDATION_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE_OBJC_CALENDAR_FOUNDATION_LIBRARY)
      #
      # Add MULLE_OBJC_CALENDAR_FOUNDATION_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark MulleObjCCalendarFoundation no-cmake-add`
      #
      set( ALL_LOAD_DEPENDENCY_LIBRARIES
         ${ALL_LOAD_DEPENDENCY_LIBRARIES}
         ${MULLE_OBJC_CALENDAR_FOUNDATION_LIBRARY}
         CACHE INTERNAL "need to cache this"
      )
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark MulleObjCCalendarFoundation no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE_OBJC_CALENDAR_FOUNDATION_ROOT "${MULLE_OBJC_CALENDAR_FOUNDATION_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_CALENDAR_FOUNDATION_ROOT "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_ROOT}" DIRECTORY)
      #
      #
      # Append header directory to user search path.
      # Disable with: `mulle-sourcetree mark MulleObjCCalendarFoundation no-cmake-searchpath`
      #
      foreach( _TMP_MULLE_OBJC_CALENDAR_FOUNDATION_NAME "MulleObjCCalendarFoundation")
         set( _TMP_MULLE_OBJC_CALENDAR_FOUNDATION_DIR "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_NAME}")
         if( IS_DIRECTORY "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_DIR}")
            set( INHERITED_INCLUDE_DIRS
               ${INHERITED_INCLUDE_DIRS}
               "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_DIR}"
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark MulleObjCCalendarFoundation no-cmake-dependency`
      #
      foreach( _TMP_MULLE_OBJC_CALENDAR_FOUNDATION_NAME "MulleObjCCalendarFoundation")
         set( _TMP_MULLE_OBJC_CALENDAR_FOUNDATION_DIR "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( EXISTS "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            unset( MULLE_OBJC_CALENDAR_FOUNDATION_DEFINITIONS)
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_DIR}")
            #
            include( "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            #
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_DIR}")
            set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${MULLE_OBJC_CALENDAR_FOUNDATION_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_DIR}/DependenciesAndLibraries.cmake not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCLoader+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark MulleObjCCalendarFoundation no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_MULLE_OBJC_CALENDAR_FOUNDATION_NAME "MulleObjCCalendarFoundation")
            set( _TMP_MULLE_OBJC_CALENDAR_FOUNDATION_FILE "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_NAME}/MulleObjCLoader+${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_NAME}.h")
            if( EXISTS "${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_FILE}")
               set( INHERITED_OBJC_LOADERS
                  ${INHERITED_OBJC_LOADERS}
                  ${_TMP_MULLE_OBJC_CALENDAR_FOUNDATION_FILE}
                  CACHE INTERNAL "need to cache this"
               )
               break()
            endif()
         endforeach()
      endif()
   else()
      # Enable with: `mulle-sourcetree mark MulleObjCCalendarFoundation require`
      message( STATUS "MULLE_OBJC_CALENDAR_FOUNDATION_LIBRARY is missing but it is marked as \"no-require\"")
   endif()
endif()


#
# Generated from sourcetree: C48EE179-39A6-466D-A07E-37ECC02D20A4;MulleObjCMathFoundation;no-require,no-singlephase;
# Disable with : `mulle-sourcetree mark MulleObjCMathFoundation no-link`
# Disable for this platform: `mulle-sourcetree mark MulleObjCMathFoundation no-cmake-platform-darwin`
#
if( NOT MULLE_OBJC_MATH_FOUNDATION_LIBRARY)
   find_library( MULLE_OBJC_MATH_FOUNDATION_LIBRARY NAMES ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjCMathFoundation${CMAKE_STATIC_LIBRARY_SUFFIX} MulleObjCMathFoundation NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH)
   message( STATUS "MULLE_OBJC_MATH_FOUNDATION_LIBRARY is ${MULLE_OBJC_MATH_FOUNDATION_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE_OBJC_MATH_FOUNDATION_LIBRARY)
      #
      # Add MULLE_OBJC_MATH_FOUNDATION_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark MulleObjCMathFoundation no-cmake-add`
      #
      set( ALL_LOAD_DEPENDENCY_LIBRARIES
         ${ALL_LOAD_DEPENDENCY_LIBRARIES}
         ${MULLE_OBJC_MATH_FOUNDATION_LIBRARY}
         CACHE INTERNAL "need to cache this"
      )
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark MulleObjCMathFoundation no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE_OBJC_MATH_FOUNDATION_ROOT "${MULLE_OBJC_MATH_FOUNDATION_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_MATH_FOUNDATION_ROOT "${_TMP_MULLE_OBJC_MATH_FOUNDATION_ROOT}" DIRECTORY)
      #
      #
      # Append header directory to user search path.
      # Disable with: `mulle-sourcetree mark MulleObjCMathFoundation no-cmake-searchpath`
      #
      foreach( _TMP_MULLE_OBJC_MATH_FOUNDATION_NAME "MulleObjCMathFoundation")
         set( _TMP_MULLE_OBJC_MATH_FOUNDATION_DIR "${_TMP_MULLE_OBJC_MATH_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_MATH_FOUNDATION_NAME}")
         if( IS_DIRECTORY "${_TMP_MULLE_OBJC_MATH_FOUNDATION_DIR}")
            set( INHERITED_INCLUDE_DIRS
               ${INHERITED_INCLUDE_DIRS}
               "${_TMP_MULLE_OBJC_MATH_FOUNDATION_DIR}"
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_MATH_FOUNDATION_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark MulleObjCMathFoundation no-cmake-dependency`
      #
      foreach( _TMP_MULLE_OBJC_MATH_FOUNDATION_NAME "MulleObjCMathFoundation")
         set( _TMP_MULLE_OBJC_MATH_FOUNDATION_DIR "${_TMP_MULLE_OBJC_MATH_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_MATH_FOUNDATION_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( EXISTS "${_TMP_MULLE_OBJC_MATH_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            unset( MULLE_OBJC_MATH_FOUNDATION_DEFINITIONS)
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_MATH_FOUNDATION_DIR}")
            #
            include( "${_TMP_MULLE_OBJC_MATH_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            #
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_MATH_FOUNDATION_DIR}")
            set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${MULLE_OBJC_MATH_FOUNDATION_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_MATH_FOUNDATION_DIR}/DependenciesAndLibraries.cmake not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCLoader+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark MulleObjCMathFoundation no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_MULLE_OBJC_MATH_FOUNDATION_NAME "MulleObjCMathFoundation")
            set( _TMP_MULLE_OBJC_MATH_FOUNDATION_FILE "${_TMP_MULLE_OBJC_MATH_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_MATH_FOUNDATION_NAME}/MulleObjCLoader+${_TMP_MULLE_OBJC_MATH_FOUNDATION_NAME}.h")
            if( EXISTS "${_TMP_MULLE_OBJC_MATH_FOUNDATION_FILE}")
               set( INHERITED_OBJC_LOADERS
                  ${INHERITED_OBJC_LOADERS}
                  ${_TMP_MULLE_OBJC_MATH_FOUNDATION_FILE}
                  CACHE INTERNAL "need to cache this"
               )
               break()
            endif()
         endforeach()
      endif()
   else()
      # Enable with: `mulle-sourcetree mark MulleObjCMathFoundation require`
      message( STATUS "MULLE_OBJC_MATH_FOUNDATION_LIBRARY is missing but it is marked as \"no-require\"")
   endif()
endif()


#
# Generated from sourcetree: df7054ac-99cd-4386-b5fc-cbce1eaf009e;MulleObjCUnicodeFoundation;no-singlephase;
# Disable with : `mulle-sourcetree mark MulleObjCUnicodeFoundation no-link`
# Disable for this platform: `mulle-sourcetree mark MulleObjCUnicodeFoundation no-cmake-platform-darwin`
#
if( NOT MULLE_OBJC_UNICODE_FOUNDATION_LIBRARY)
   find_library( MULLE_OBJC_UNICODE_FOUNDATION_LIBRARY NAMES ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjCUnicodeFoundation${CMAKE_STATIC_LIBRARY_SUFFIX} MulleObjCUnicodeFoundation NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH)
   message( STATUS "MULLE_OBJC_UNICODE_FOUNDATION_LIBRARY is ${MULLE_OBJC_UNICODE_FOUNDATION_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE_OBJC_UNICODE_FOUNDATION_LIBRARY)
      #
      # Add MULLE_OBJC_UNICODE_FOUNDATION_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark MulleObjCUnicodeFoundation no-cmake-add`
      #
      set( ALL_LOAD_DEPENDENCY_LIBRARIES
         ${ALL_LOAD_DEPENDENCY_LIBRARIES}
         ${MULLE_OBJC_UNICODE_FOUNDATION_LIBRARY}
         CACHE INTERNAL "need to cache this"
      )
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark MulleObjCUnicodeFoundation no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE_OBJC_UNICODE_FOUNDATION_ROOT "${MULLE_OBJC_UNICODE_FOUNDATION_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_UNICODE_FOUNDATION_ROOT "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_ROOT}" DIRECTORY)
      #
      #
      # Append header directory to user search path.
      # Disable with: `mulle-sourcetree mark MulleObjCUnicodeFoundation no-cmake-searchpath`
      #
      foreach( _TMP_MULLE_OBJC_UNICODE_FOUNDATION_NAME "MulleObjCUnicodeFoundation")
         set( _TMP_MULLE_OBJC_UNICODE_FOUNDATION_DIR "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_NAME}")
         if( IS_DIRECTORY "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_DIR}")
            set( INHERITED_INCLUDE_DIRS
               ${INHERITED_INCLUDE_DIRS}
               "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_DIR}"
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark MulleObjCUnicodeFoundation no-cmake-dependency`
      #
      foreach( _TMP_MULLE_OBJC_UNICODE_FOUNDATION_NAME "MulleObjCUnicodeFoundation")
         set( _TMP_MULLE_OBJC_UNICODE_FOUNDATION_DIR "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( EXISTS "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            unset( MULLE_OBJC_UNICODE_FOUNDATION_DEFINITIONS)
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_DIR}")
            #
            include( "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            #
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_DIR}")
            set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${MULLE_OBJC_UNICODE_FOUNDATION_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_DIR}/DependenciesAndLibraries.cmake not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCLoader+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark MulleObjCUnicodeFoundation no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_MULLE_OBJC_UNICODE_FOUNDATION_NAME "MulleObjCUnicodeFoundation")
            set( _TMP_MULLE_OBJC_UNICODE_FOUNDATION_FILE "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_NAME}/MulleObjCLoader+${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_NAME}.h")
            if( EXISTS "${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_FILE}")
               set( INHERITED_OBJC_LOADERS
                  ${INHERITED_OBJC_LOADERS}
                  ${_TMP_MULLE_OBJC_UNICODE_FOUNDATION_FILE}
                  CACHE INTERNAL "need to cache this"
               )
               break()
            endif()
         endforeach()
      endif()
   else()
      # Disable with: `mulle-sourcetree mark MulleObjCUnicodeFoundation no-require-link`
      message( FATAL_ERROR "MULLE_OBJC_UNICODE_FOUNDATION_LIBRARY was not found")
   endif()
endif()


#
# Generated from sourcetree: 113F8278-0CA5-4813-9285-8EB1110AD9D9;MulleObjCArchiverFoundation;no-require,no-singlephase;
# Disable with : `mulle-sourcetree mark MulleObjCArchiverFoundation no-link`
# Disable for this platform: `mulle-sourcetree mark MulleObjCArchiverFoundation no-cmake-platform-darwin`
#
if( NOT MULLE_OBJC_ARCHIVER_FOUNDATION_LIBRARY)
   find_library( MULLE_OBJC_ARCHIVER_FOUNDATION_LIBRARY NAMES ${CMAKE_STATIC_LIBRARY_PREFIX}MulleObjCArchiverFoundation${CMAKE_STATIC_LIBRARY_SUFFIX} MulleObjCArchiverFoundation NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH)
   message( STATUS "MULLE_OBJC_ARCHIVER_FOUNDATION_LIBRARY is ${MULLE_OBJC_ARCHIVER_FOUNDATION_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE_OBJC_ARCHIVER_FOUNDATION_LIBRARY)
      #
      # Add MULLE_OBJC_ARCHIVER_FOUNDATION_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark MulleObjCArchiverFoundation no-cmake-add`
      #
      set( ALL_LOAD_DEPENDENCY_LIBRARIES
         ${ALL_LOAD_DEPENDENCY_LIBRARIES}
         ${MULLE_OBJC_ARCHIVER_FOUNDATION_LIBRARY}
         CACHE INTERNAL "need to cache this"
      )
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark MulleObjCArchiverFoundation no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_ROOT "${MULLE_OBJC_ARCHIVER_FOUNDATION_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_ROOT "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_ROOT}" DIRECTORY)
      #
      #
      # Append header directory to user search path.
      # Disable with: `mulle-sourcetree mark MulleObjCArchiverFoundation no-cmake-searchpath`
      #
      foreach( _TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_NAME "MulleObjCArchiverFoundation")
         set( _TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_DIR "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_NAME}")
         if( IS_DIRECTORY "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_DIR}")
            set( INHERITED_INCLUDE_DIRS
               ${INHERITED_INCLUDE_DIRS}
               "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_DIR}"
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark MulleObjCArchiverFoundation no-cmake-dependency`
      #
      foreach( _TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_NAME "MulleObjCArchiverFoundation")
         set( _TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_DIR "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( EXISTS "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            unset( MULLE_OBJC_ARCHIVER_FOUNDATION_DEFINITIONS)
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_DIR}")
            #
            include( "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_DIR}/DependenciesAndLibraries.cmake")
            #
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_DIR}")
            set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${MULLE_OBJC_ARCHIVER_FOUNDATION_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
            )
            break()
         else()
            message( STATUS "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_DIR}/DependenciesAndLibraries.cmake not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCLoader+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark MulleObjCArchiverFoundation no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_NAME "MulleObjCArchiverFoundation")
            set( _TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_FILE "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_ROOT}/include/${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_NAME}/MulleObjCLoader+${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_NAME}.h")
            if( EXISTS "${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_FILE}")
               set( INHERITED_OBJC_LOADERS
                  ${INHERITED_OBJC_LOADERS}
                  ${_TMP_MULLE_OBJC_ARCHIVER_FOUNDATION_FILE}
                  CACHE INTERNAL "need to cache this"
               )
               break()
            endif()
         endforeach()
      endif()
   else()
      # Enable with: `mulle-sourcetree mark MulleObjCArchiverFoundation require`
      message( STATUS "MULLE_OBJC_ARCHIVER_FOUNDATION_LIBRARY is missing but it is marked as \"no-require\"")
   endif()
endif()
