#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleFoundation-import-private.h
src/reflect/_MulleFoundation-include-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
src/include-private.h
src/mulle-foundation-setup-private.h
src/mulle-foundation-startup-private.inc
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleFoundation-import.h
src/reflect/_MulleFoundation-include.h
)

set( PUBLIC_HEADERS
src/MulleFoundation.h
src/MulleObjCLoader+MulleFoundation.h
src/NSConditionLock.h
src/import.h
src/include.h
src/version.h
)

