/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use DACD462C-D0AC-4D93-81A6-4E0972215046 instead of MulleObjCOSFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCOSFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCOSFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCOSFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCOSFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCOSFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCOSFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCOSFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#ifdef __has_include
# if __has_include(<MulleObjCOSFoundation/MulleObjCOSFoundation.h>)
#  import <MulleObjCOSFoundation/MulleObjCOSFoundation.h>   // MulleObjCOSFoundation
#  define HAVE_LIB_MULLE_OBJC_OS_FOUNDATION
# endif
#endif

// You can tweak the following #import with these commands.
// (Use 3C6EAD75-99C0-482F-AAA7-CFB194733AEC instead of MulleObjCKVCFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCKVCFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCKVCFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCKVCFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCKVCFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCKVCFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCKVCFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCKVCFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#ifdef __has_include
# if __has_include(<MulleObjCKVCFoundation/MulleObjCKVCFoundation.h>)
#  import <MulleObjCKVCFoundation/MulleObjCKVCFoundation.h>   // MulleObjCKVCFoundation
#  define HAVE_LIB_MULLE_OBJC_KVC_FOUNDATION
# endif
#endif

// You can tweak the following #import with these commands.
// (Use 41549518-5DAC-4A6A-82A9-E2CAABE3828F instead of MulleObjCDecimalFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCDecimalFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCDecimalFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCDecimalFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCDecimalFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCDecimalFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCDecimalFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCDecimalFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#ifdef __has_include
# if __has_include(<MulleObjCDecimalFoundation/MulleObjCDecimalFoundation.h>)
#  import <MulleObjCDecimalFoundation/MulleObjCDecimalFoundation.h>   // MulleObjCDecimalFoundation
#  define HAVE_LIB_MULLE_OBJC_DECIMAL_FOUNDATION
# endif
#endif

// You can tweak the following #import with these commands.
// (Use 1D103583-A637-4819-9255-3A265C80E49A instead of MulleObjCCalendarFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCCalendarFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCCalendarFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCCalendarFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCCalendarFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCCalendarFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCCalendarFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCCalendarFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#ifdef __has_include
# if __has_include(<MulleObjCCalendarFoundation/MulleObjCCalendarFoundation.h>)
#  import <MulleObjCCalendarFoundation/MulleObjCCalendarFoundation.h>   // MulleObjCCalendarFoundation
#  define HAVE_LIB_MULLE_OBJC_CALENDAR_FOUNDATION
# endif
#endif

// You can tweak the following #import with these commands.
// (Use C48EE179-39A6-466D-A07E-37ECC02D20A4 instead of MulleObjCMathFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCMathFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCMathFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCMathFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCMathFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCMathFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCMathFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCMathFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#ifdef __has_include
# if __has_include(<MulleObjCMathFoundation/MulleObjCMathFoundation.h>)
#  import <MulleObjCMathFoundation/MulleObjCMathFoundation.h>   // MulleObjCMathFoundation
#  define HAVE_LIB_MULLE_OBJC_MATH_FOUNDATION
# endif
#endif

// You can tweak the following #import with these commands.
// (Use df7054ac-99cd-4386-b5fc-cbce1eaf009e instead of MulleObjCUnicodeFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCUnicodeFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCUnicodeFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCUnicodeFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCUnicodeFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCUnicodeFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCUnicodeFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCUnicodeFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleObjCUnicodeFoundation/MulleObjCUnicodeFoundation.h>   // MulleObjCUnicodeFoundation

// You can tweak the following #import with these commands.
// (Use 113F8278-0CA5-4813-9285-8EB1110AD9D9 instead of MulleObjCArchiverFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCArchiverFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCArchiverFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCArchiverFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCArchiverFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCArchiverFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCArchiverFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCArchiverFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#ifdef __has_include
# if __has_include(<MulleObjCArchiverFoundation/MulleObjCArchiverFoundation.h>)
#  import <MulleObjCArchiverFoundation/MulleObjCArchiverFoundation.h>   // MulleObjCArchiverFoundation
#  define HAVE_LIB_MULLE_OBJC_ARCHIVER_FOUNDATION
# endif
#endif

#ifdef __has_include
# if __has_include( "_MulleFoundation-include.h")
#  include "_MulleFoundation-include.h"
# endif
#endif

