/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _MulleFoundation_import_h__
#define _MulleFoundation_import_h__

// How to tweak the following MulleObjCOSFoundation #import
//    remove:             `mulle-sourcetree mark MulleObjCOSFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCOSFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCOSFoundation [no-]import`
//    toggle localheader: `mulle-sourcetree mark MulleObjCOSFoundation [no-]localheader`
//    toggle public:      `mulle-sourcetree mark MulleObjCOSFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCOSFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCOSFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCOSFoundation/MulleObjCOSFoundation.h>)
#   import <MulleObjCOSFoundation/MulleObjCOSFoundation.h>   // MulleObjCOSFoundation
#   define HAVE_LIB_MULLE_OBJC_OS_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCKVCFoundation #import
//    remove:             `mulle-sourcetree mark MulleObjCKVCFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCKVCFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCKVCFoundation [no-]import`
//    toggle localheader: `mulle-sourcetree mark MulleObjCKVCFoundation [no-]localheader`
//    toggle public:      `mulle-sourcetree mark MulleObjCKVCFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCKVCFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCKVCFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCKVCFoundation/MulleObjCKVCFoundation.h>)
#   import <MulleObjCKVCFoundation/MulleObjCKVCFoundation.h>   // MulleObjCKVCFoundation
#   define HAVE_LIB_MULLE_OBJC_KVC_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCDecimalFoundation #import
//    remove:             `mulle-sourcetree mark MulleObjCDecimalFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCDecimalFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCDecimalFoundation [no-]import`
//    toggle localheader: `mulle-sourcetree mark MulleObjCDecimalFoundation [no-]localheader`
//    toggle public:      `mulle-sourcetree mark MulleObjCDecimalFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCDecimalFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCDecimalFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCDecimalFoundation/MulleObjCDecimalFoundation.h>)
#   import <MulleObjCDecimalFoundation/MulleObjCDecimalFoundation.h>   // MulleObjCDecimalFoundation
#   define HAVE_LIB_MULLE_OBJC_DECIMAL_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCCalendarFoundation #import
//    remove:             `mulle-sourcetree mark MulleObjCCalendarFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCCalendarFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCCalendarFoundation [no-]import`
//    toggle localheader: `mulle-sourcetree mark MulleObjCCalendarFoundation [no-]localheader`
//    toggle public:      `mulle-sourcetree mark MulleObjCCalendarFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCCalendarFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCCalendarFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCCalendarFoundation/MulleObjCCalendarFoundation.h>)
#   import <MulleObjCCalendarFoundation/MulleObjCCalendarFoundation.h>   // MulleObjCCalendarFoundation
#   define HAVE_LIB_MULLE_OBJC_CALENDAR_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCMathFoundation #import
//    remove:             `mulle-sourcetree mark MulleObjCMathFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCMathFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCMathFoundation [no-]import`
//    toggle localheader: `mulle-sourcetree mark MulleObjCMathFoundation [no-]localheader`
//    toggle public:      `mulle-sourcetree mark MulleObjCMathFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCMathFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCMathFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCMathFoundation/MulleObjCMathFoundation.h>)
#   import <MulleObjCMathFoundation/MulleObjCMathFoundation.h>   // MulleObjCMathFoundation
#   define HAVE_LIB_MULLE_OBJC_MATH_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCUnicodeFoundation #import
//    remove:             `mulle-sourcetree mark MulleObjCUnicodeFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCUnicodeFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCUnicodeFoundation [no-]import`
//    toggle localheader: `mulle-sourcetree mark MulleObjCUnicodeFoundation [no-]localheader`
//    toggle public:      `mulle-sourcetree mark MulleObjCUnicodeFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCUnicodeFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCUnicodeFoundation no-os-<osname>`
# if defined( __has_include) && __has_include("MulleObjCUnicodeFoundation.h")
#   import "MulleObjCUnicodeFoundation.h"   // MulleObjCUnicodeFoundation
# else
#   import <MulleObjCUnicodeFoundation/MulleObjCUnicodeFoundation.h>   // MulleObjCUnicodeFoundation
# endif

#ifdef __has_include
# if __has_include( "_MulleFoundation-include.h")
#  include "_MulleFoundation-include.h"
# endif
#endif


#endif
