      { @selector( MulleObjCLoader), @selector( MulleFoundationBase) },      // 47a9beb6;MulleObjCLoader;efab19ea;MulleFoundationBase
      { @selector( MulleObjCLoader), @selector( MulleObjCCalendarFoundation) },      // 47a9beb6;MulleObjCLoader;6b608d36;MulleObjCCalendarFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCDecimalFoundation) },      // 47a9beb6;MulleObjCLoader;f04a7a28;MulleObjCDecimalFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCOSFoundation) },      // 47a9beb6;MulleObjCLoader;94ffe970;MulleObjCOSFoundation
