      { @selector( MulleObjCLoader), @selector( MulleObjCCalendarFoundation) },      // 47a9beb6;MulleObjCLoader;6b608d36;MulleObjCCalendarFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCKVCFoundation) },      // 47a9beb6;MulleObjCLoader;4f2544f7;MulleObjCKVCFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCMathFoundation) },      // 47a9beb6;MulleObjCLoader;37da74b9;MulleObjCMathFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCOSFoundation) },      // 47a9beb6;MulleObjCLoader;94ffe970;MulleObjCOSFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCUnicodeFoundation) },      // 47a9beb6;MulleObjCLoader;ab2bbded;MulleObjCUnicodeFoundation
      { @selector( NSConditionLock), MULLE_OBJC_NO_CATEGORYID },      // 5e0deecf;NSConditionLock;;
