      { @selector( MulleObjCDeps), @selector( MulleFoundationBase) },      // 3c20656f;MulleObjCDeps;efab19ea;MulleFoundationBase
      { @selector( MulleObjCDeps), @selector( MulleObjCCalendarFoundation) },      // 3c20656f;MulleObjCDeps;6b608d36;MulleObjCCalendarFoundation
      { @selector( MulleObjCDeps), @selector( MulleObjCDecimalFoundation) },      // 3c20656f;MulleObjCDeps;f04a7a28;MulleObjCDecimalFoundation
      { @selector( MulleObjCDeps), @selector( MulleObjCOSFoundation) },      // 3c20656f;MulleObjCDeps;94ffe970;MulleObjCOSFoundation
