/*
* This file will be regenerated by `mulle-sde update|monitor`.
* Edits will be lost.
* Suppress this file with MULLE_SDE_IMPORT_FILENAME NONE|DISABLE.
*/

#ifndef _mulle_foundation_import_h__
#define _mulle_foundation_import_h__

# import <MulleObjCOSFoundation/MulleObjCOSFoundation.h>   // MulleObjCOSFoundation

# if __has_include(<MulleObjCExpatFoundation/MulleObjCExpatFoundation.h>)
#  import <MulleObjCExpatFoundation/MulleObjCExpatFoundation.h>   // MulleObjCExpatFoundation
# endif

# import <MulleObjCKVCFoundation/MulleObjCKVCFoundation.h>   // MulleObjCKVCFoundation

#endif
