/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_foundation_import_h__
#define _mulle_foundation_import_h__

// How to tweak the following MulleObjCOSFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCOSFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCOSFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCOSFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCOSFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCOSFoundation no-os-<osname>`
# import <MulleObjCOSFoundation/MulleObjCOSFoundation.h>   // MulleObjCOSFoundation

// How to tweak the following MulleObjCExpatFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCExpatFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCExpatFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCExpatFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCExpatFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCExpatFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCExpatFoundation/MulleObjCExpatFoundation.h>)
#   import <MulleObjCExpatFoundation/MulleObjCExpatFoundation.h>   // MulleObjCExpatFoundation
#   define HAVE_LIB_MULLEOBJCEXPATFOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCKVCFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCKVCFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCKVCFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCKVCFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCKVCFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCKVCFoundation no-os-<osname>`
# import <MulleObjCKVCFoundation/MulleObjCKVCFoundation.h>   // MulleObjCKVCFoundation

// How to tweak the following MulleObjCDecimalFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCDecimalFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCDecimalFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCDecimalFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCDecimalFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCDecimalFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCDecimalFoundation/MulleObjCDecimalFoundation.h>)
#   import <MulleObjCDecimalFoundation/MulleObjCDecimalFoundation.h>   // MulleObjCDecimalFoundation
#   define HAVE_LIB_MULLEOBJCDECIMALFOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCJSMNFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCJSMNFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCJSMNFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCJSMNFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCJSMNFoundation/MulleObjCJSMNFoundation.h>)
#   import <MulleObjCJSMNFoundation/MulleObjCJSMNFoundation.h>   // MulleObjCJSMNFoundation
#   define HAVE_LIB_MULLEOBJCJSMNFOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCCurlFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCCurlFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCCurlFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCCurlFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCCurlFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCCurlFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCCurlFoundation/MulleObjCCurlFoundation.h>)
#   import <MulleObjCCurlFoundation/MulleObjCCurlFoundation.h>   // MulleObjCCurlFoundation
#   define HAVE_LIB_MULLEOBJCCURLFOUNDATION
#  endif
# endif

#include "_MulleFoundation-include.h"


#endif
