/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_foundation_include_h__
#define _mulle_foundation_include_h__

# if __has_include(<MulleObjCDecimalFoundation/MulleObjCDecimalFoundation.h>)
#  include <MulleObjCDecimalFoundation/MulleObjCDecimalFoundation.h>   // MulleObjCDecimalFoundation
# endif

#endif
