/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_foundation_import_h__
#define _mulle_foundation_import_h__

// How to tweak the following MulleObjCOSFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCOSFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCOSFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCOSFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCOSFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCOSFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCOSFoundation/MulleObjCOSFoundation.h>)
#   import <MulleObjCOSFoundation/MulleObjCOSFoundation.h>   // MulleObjCOSFoundation
#   define HAVE_LIB_MULLE_OBJC_OS_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCExpatFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCExpatFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCExpatFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCExpatFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCExpatFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCExpatFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCExpatFoundation/MulleObjCExpatFoundation.h>)
#   import <MulleObjCExpatFoundation/MulleObjCExpatFoundation.h>   // MulleObjCExpatFoundation
#   define HAVE_LIB_MULLE_OBJC_EXPAT_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCKVCFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCKVCFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCKVCFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCKVCFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCKVCFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCKVCFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCKVCFoundation/MulleObjCKVCFoundation.h>)
#   import <MulleObjCKVCFoundation/MulleObjCKVCFoundation.h>   // MulleObjCKVCFoundation
#   define HAVE_LIB_MULLE_OBJC_KVC_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCDecimalFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCDecimalFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCDecimalFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCDecimalFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCDecimalFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCDecimalFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCDecimalFoundation/MulleObjCDecimalFoundation.h>)
#   import <MulleObjCDecimalFoundation/MulleObjCDecimalFoundation.h>   // MulleObjCDecimalFoundation
#   define HAVE_LIB_MULLE_OBJC_DECIMAL_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCJSMNFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCJSMNFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCJSMNFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCJSMNFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCJSMNFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCJSMNFoundation/MulleObjCJSMNFoundation.h>)
#   import <MulleObjCJSMNFoundation/MulleObjCJSMNFoundation.h>   // MulleObjCJSMNFoundation
#   define HAVE_LIB_MULLE_OBJC_JSMN_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCCalendarFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCCalendarFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCCalendarFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCCalendarFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCCalendarFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCCalendarFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCCalendarFoundation/MulleObjCCalendarFoundation.h>)
#   import <MulleObjCCalendarFoundation/MulleObjCCalendarFoundation.h>   // MulleObjCCalendarFoundation
#   define HAVE_LIB_MULLE_OBJC_CALENDAR_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCMathFoundation #import
//    remove:          `mulle-sourcetree mark MulleObjCMathFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleObjCMathFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleObjCMathFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleObjCMathFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleObjCMathFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCMathFoundation/MulleObjCMathFoundation.h>)
#   import <MulleObjCMathFoundation/MulleObjCMathFoundation.h>   // MulleObjCMathFoundation
#   define HAVE_LIB_MULLE_OBJC_MATH_FOUNDATION
#  endif
# endif

#include "_MulleFoundation-include.h"


#endif
