      { @selector( MulleObjCLoader), @selector( MulleObjCExpatFoundation) },      // 58bd58d3;MulleObjCLoader;3c626dbf;MulleObjCExpatFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 58bd58d3;MulleObjCLoader;307411f3;MulleObjCInetFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCKVCFoundation) },      // 58bd58d3;MulleObjCLoader;c0454973;MulleObjCKVCFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 58bd58d3;MulleObjCLoader;efe3d73e;MulleObjCStandardFoundation
