      { @selector( MulleObjCLoader), @selector( MulleObjCBSDFoundation) },      // 58bd58d3;MulleObjCLoader;578a7a2a;MulleObjCBSDFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCDarwinFoundation) },      // 58bd58d3;MulleObjCLoader;bfc4e780;MulleObjCDarwinFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCExpatFoundation) },      // 58bd58d3;MulleObjCLoader;3c626dbf;MulleObjCExpatFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 58bd58d3;MulleObjCLoader;307411f3;MulleObjCInetFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCKVCFoundation) },      // 58bd58d3;MulleObjCLoader;c0454973;MulleObjCKVCFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCOSBaseFoundation) },      // 58bd58d3;MulleObjCLoader;8aabd7dc;MulleObjCOSBaseFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCPosixFoundation) },      // 58bd58d3;MulleObjCLoader;bf9cc404;MulleObjCPosixFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 58bd58d3;MulleObjCLoader;efe3d73e;MulleObjCStandardFoundation
