      { @selector( MulleObjCLoader), @selector( MulleObjCExpatFoundation) },      // 58bd58d3,3c626dbf
      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 58bd58d3,307411f3
      { @selector( MulleObjCLoader), @selector( MulleObjCKVCFoundation) },      // 58bd58d3,c0454973
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 58bd58d3,efe3d73e
