      { @selector( MulleObjCLoader), @selector( MulleObjCCurlFoundation) },      // 47a9beb6;MulleObjCLoader;fd75d574;MulleObjCCurlFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCDecimalFoundation) },      // 47a9beb6;MulleObjCLoader;f04a7a28;MulleObjCDecimalFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCExpatFoundation) },      // 47a9beb6;MulleObjCLoader;e5f6fc77;MulleObjCExpatFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCJSMNFoundation) },      // 47a9beb6;MulleObjCLoader;383fe71a;MulleObjCJSMNFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCKVCFoundation) },      // 47a9beb6;MulleObjCLoader;4f2544f7;MulleObjCKVCFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCOSFoundation) },      // 47a9beb6;MulleObjCLoader;94ffe970;MulleObjCOSFoundation
      { @selector( MulleObjCJSMNParser), @selector( MulleObjCCurlParser) },      // 548dde79;MulleObjCJSMNParser;cea2d1dd;MulleObjCCurlParser
      { @selector( NSConditionLock), MULLE_OBJC_NO_CATEGORYID },      // 5e0deecf;NSConditionLock;;
