      { @selector( MulleObjCLoader), @selector( MulleObjCCalendarFoundation) },      // 47a9beb6;MulleObjCLoader;6b608d36;MulleObjCCalendarFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCDecimalFoundation) },      // 47a9beb6;MulleObjCLoader;f04a7a28;MulleObjCDecimalFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCExpatFoundation) },      // 47a9beb6;MulleObjCLoader;e5f6fc77;MulleObjCExpatFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCJSMNFoundation) },      // 47a9beb6;MulleObjCLoader;383fe71a;MulleObjCJSMNFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCKVCFoundation) },      // 47a9beb6;MulleObjCLoader;4f2544f7;MulleObjCKVCFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCMathFoundation) },      // 47a9beb6;MulleObjCLoader;37da74b9;MulleObjCMathFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCOSFoundation) },      // 47a9beb6;MulleObjCLoader;94ffe970;MulleObjCOSFoundation
      { @selector( NSConditionLock), MULLE_OBJC_NO_CATEGORYID },      // 5e0deecf;NSConditionLock;;
