#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleFoundation.m
src/NSConditionLock.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleFoundation.m
)

set( STANDALONE_SOURCES
src/mulle-foundation-standalone.m
)
